services:

  promtail-obol:
    image: grafana/promtail:latest
    user: root
    volumes:
      - ./promtail-obol:/etc/promtail
      - promtail-obol-data:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_ROOT:-/var/lib/docker}/containers:/var/lib/docker/containers:ro,rslave
    entrypoint: ./etc/promtail/entrypoint.sh
    command: ["/usr/bin/promtail"]
    environment:
      CHARON_LOKI_ADDRESSES: ${OBOL_CHARON_REMOTE_LOKI_ADDRESSES}
      CLUSTER_NAME: ${OBOL_CLUSTER_NAME}
      CLUSTER_PEER: ${OBOL_CLUSTER_PEER}
    restart: "unless-stopped"
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=9080
      - metrics.instance=obol-promtail
      - metrics.network=${NETWORK}

volumes:
  promtail-obol-data:
