name: Test Caplin and Erigon

defaults:
  run:
    shell: bash

on:
  push:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    branches: [main]

jobs:
  test-caplin-erigon:
    if: |
      contains(github.event.pull_request.labels.*.name, 'test-caplin') ||
      contains(github.event.pull_request.labels.*.name, 'test-all') ||
      github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Create .env file
        run: cp default.env .env
      - name: Set Caplin/Erigon
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=erigon.yml:caplin-ports.yml:lodestar-vc-only.yml
          var=COMPOSE_FILE
          set_value_in_env
          FEE_RECIPIENT=0xDccf8451070a86183eE70D330C4c43b686E9CF86
          var=FEE_RECIPIENT
          set_value_in_env
          CL_NODE=http://execution:5052
          var=CL_NODE
          set_value_in_env
      - name: Start Caplin/Erigon w/ Lodestar VC
        run: ./ethd up
      - name: Pause for 30 seconds
        run: sleep 30
      - name: Test Caplin/Erigon
        run: ./.github/check-service.sh execution
      - name: Test VC
        run: ./.github/check-service.sh validator
